version: "2"

run:
 # Include test files or not.
 # Default: true
 tests: false
 # Timeout for total work, e.g. 30s, 5m, 5m30s.
 # Default: 0 (disabled)
 timeout: 5m

issues:
 # Maximum issues count per one linter.
 # Set to 0 to disable.
 # Default: 50
 max-issues-per-linter: 0
 # Maximum count of issues with the same text.
 # Set to 0 to disable.
 # Default: 3
 max-same-issues: 0
